-- =============================================================================
-- BIDA ML Starter - Berechtigungen fuer die Rolle ML_DEVELOPER (Referenz)
-- =============================================================================
-- PROD_ML (Schemas INFERENCE, REGISTRY, MONITORING) existiert bereits und wird
-- vom DWH-Team verwaltet. Dieses Script dokumentiert, welche Rechte ein
-- ML-Entwickler braucht. Nur ausfuehren (Admin), wenn ein neuer User oder ein
-- neues Quellschema dazukommt.
-- =============================================================================

USE ROLE SECURITYADMIN;

-- 1. Warehouse
GRANT USAGE ON WAREHOUSE CONSUMER TO ROLE ML_DEVELOPER;

-- 2. Schreibrechte auf PROD_ML (Outputs der Notebooks)
GRANT USAGE ON DATABASE PROD_ML TO ROLE ML_DEVELOPER;

GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE
  ON SCHEMA PROD_ML.INFERENCE  TO ROLE ML_DEVELOPER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE
  ON SCHEMA PROD_ML.REGISTRY   TO ROLE ML_DEVELOPER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE
  ON SCHEMA PROD_ML.MONITORING TO ROLE ML_DEVELOPER;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES    IN SCHEMA PROD_ML.INFERENCE  TO ROLE ML_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PROD_ML.INFERENCE  TO ROLE ML_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES    IN SCHEMA PROD_ML.REGISTRY   TO ROLE ML_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PROD_ML.REGISTRY   TO ROLE ML_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES    IN SCHEMA PROD_ML.MONITORING TO ROLE ML_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PROD_ML.MONITORING TO ROLE ML_DEVELOPER;

GRANT SELECT ON ALL VIEWS    IN DATABASE PROD_ML TO ROLE ML_DEVELOPER;
GRANT SELECT ON FUTURE VIEWS IN DATABASE PROD_ML TO ROLE ML_DEVELOPER;

-- 3. Leserechte auf die Quellen (PSA-Tabellen und *_90 Views in PROD_DATALAKE)
--    Pro Quellschema wiederholen (MSACCESS, WAMAS4, ML, ...)
GRANT USAGE ON DATABASE PROD_DATALAKE TO ROLE ML_DEVELOPER;

GRANT USAGE ON SCHEMA PROD_DATALAKE.MSACCESS TO ROLE ML_DEVELOPER;
GRANT SELECT ON ALL TABLES    IN SCHEMA PROD_DATALAKE.MSACCESS TO ROLE ML_DEVELOPER;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PROD_DATALAKE.MSACCESS TO ROLE ML_DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROD_DATALAKE.MSACCESS TO ROLE ML_DEVELOPER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PROD_DATALAKE.MSACCESS TO ROLE ML_DEVELOPER;

-- 4. Rolle an User zuweisen (anpassen)
-- GRANT ROLE ML_DEVELOPER TO USER toni_buehlmann;

-- 5. Key-Pair Auth pro User (Public Key aus ~/.snowflake/rsa_key.pub, ohne BEGIN/END Zeilen)
-- ALTER USER toni_buehlmann SET RSA_PUBLIC_KEY='MIIBIjANBgkqhk...';

-- 6. Pruefen
-- SHOW GRANTS TO ROLE ML_DEVELOPER;
